### Numpy Fundamenrtals
- It is a scientific computing liberary and the most important things in this liberary it is numpy array.

- And the numpy liberary is the godfather in the field of data science.


### Numpy Arrays Vs Python Sequences
- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating numpy arry

In [5]:
## np.array
## 1D array
import numpy as np
a= np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [6]:
## 2D and 3D 
b= np.array([[2,1,3],[1,2,4]])
print(b)

[[2 1 3]
 [1 2 4]]


In [7]:
c=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [8]:
## dtype
d=np.array([1,2,3],dtype=bool)
print(d)

[ True  True  True]


In [9]:
d=np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


In [10]:
##np.arange
e=np.arange(1,11,2)
print(e)


[1 3 5 7 9]


In [11]:
### with reshape
f=np.arange(1,11).reshape(2,5)
print(f)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
## np.ones and np.zero
g=np.ones((3,4))
print(g)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#np.random
np.random.random((3,4))

array([[0.81501741, 0.62820652, 0.58369241, 0.50888957],
       [0.06450514, 0.64110046, 0.34311095, 0.93579452],
       [0.23076353, 0.66299398, 0.6881361 , 0.14045266]])

In [16]:
#np.linspace
# linearly saperable point genrate in the given point 
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [17]:
## np.identity
# In identity matrix all diagonal print are ones
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Atributes 


In [18]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [20]:
# ndim # ndim tels that what type of array like 2d, 1d and 3d of data  contain 
print(a1.ndim)
print(a2.ndim)
a3.ndim

1
2


3

In [21]:
#shape
a2.shape
print(a3.shape)
a2.shape

(2, 2, 2)


(3, 4)

In [22]:

print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
#size
a3.size

8

In [24]:
a2.size

12

In [25]:
## itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [26]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int32


### changing datatype


In [27]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
#astype
# it aslo use for converting 64 bit to 32 bit 
a3.dtype

dtype('int32')

In [29]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
a3.astype

<function ndarray.astype>

#### Array Operations


In [31]:
a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(3,4)

In [32]:
##  scalar operation 

#arithmatic 
a3**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [33]:
#relational operators 
a3>3

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
### vector operation 
 # arithmatic 
a3 ** a4

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

### Array function 


In [93]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[92., 34., 41.],
       [84., 56., 69.],
       [31., 75., 45.]])

In [36]:
## max/ nin / sum/prod
print(np.max(a1))

print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))



99.0
5.0
477.0
145884727296000.0


In [37]:
## max/ nin / sum/prod
# 0-> col and 1->row

print(np.max(a1,axis=1))
print(np.min(a1,axis=1))
print(np.prod(a1,axis=1))
print(np.sum(a1,axis=1))


[99. 81. 64.]
[ 5. 30. 47.]
[  3960. 194400. 189504.]
[112. 191. 174.]


In [38]:

## max/ nin / sum/prod
# 0-> col and 1->row

print(np.max(a1,axis=0))
print(np.min(a1,axis=0))
print(np.prod(a1,axis=0))
print(np.sum(a1,axis=0))

[64. 80. 99.]
[ 5.  8. 63.]
[  9600.  30080. 505197.]
[ 99. 135. 243.]


In [39]:
# men / median / std / var
# 0-> col and 1->row

print(np.mean(a1,axis=0))
print(np.median(a1,axis=0))
print(np.std(a1,axis=0))
print(np.var(a1,axis=0))

[33. 45. 81.]
[30. 47. 81.]
[24.17988144 29.42787794 14.69693846]
[584.66666667 866.         216.        ]


In [40]:
print(np.mean(a1,axis=1))
print(np.median(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))


[37.33333333 63.66666667 58.        ]
[ 8. 80. 63.]
[43.62211468 23.80942857  7.78888096]
[1902.88888889  566.88888889   60.66666667]


In [41]:
## trigonomatry 
np.sin(a1)

array([[-0.95892427,  0.98935825, -0.99920683],
       [-0.98803162, -0.99388865, -0.62988799],
       [ 0.92002604,  0.12357312,  0.1673557 ]])

In [42]:
## dot product 
a2 = np.arange(12).reshape(3,4)
a3 =np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[ 824.,  936., 1048., 1160.],
       [ 968., 1159., 1350., 1541.],
       [ 692.,  866., 1040., 1214.]])

In [43]:
## log . exponent (exp) 
np.log(a1)

array([[1.60943791, 2.07944154, 4.59511985],
       [3.40119738, 4.38202663, 4.39444915],
       [4.15888308, 3.8501476 , 4.14313473]])

In [44]:
np.exp(a1)

array([[1.48413159e+02, 2.98095799e+03, 9.88903032e+42],
       [1.06864746e+13, 5.54062238e+34, 1.50609731e+35],
       [6.23514908e+27, 2.58131289e+20, 2.29378316e+27]])

In [45]:
# round/ floor / ceil

np.ceil(np.random.random((2,3))*100)

array([[97., 14., 32.],
       [69., 10., 70.]])

### indexing and slicing 

In [46]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [47]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a1[-1]

9

In [50]:
a2
## 2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2[1,2]

6

In [52]:
a2[2,2]

10

In [53]:
a2[1,0]

4

In [54]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
a3[1,0,1]

5

In [56]:
a3[0,1,0]

2

In [57]:
a3[0,0,0]

0

In [58]:
a3[1,1,0]

6

### slicing

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1[2:5]

array([2, 3, 4])

In [61]:
a1[2:5:2]

array([2, 4])

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a2[0,:]

array([0, 1, 2, 3])

In [64]:
a2[:,2]

array([ 2,  6, 10])

In [65]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [66]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [67]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [68]:
a2[1,::3]

array([4, 7])

In [69]:
a2[1]

array([4, 5, 6, 7])

In [70]:
a2[0:2,1:]


array([[1, 2, 3],
       [5, 6, 7]])

In [71]:
a2[1]


array([4, 5, 6, 7])

In [72]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
a3[0,1]

array([3, 4, 5])

In [76]:
a3[1,::,1]

array([10, 13, 16])

In [77]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

#### Iterating 

In [78]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [79]:
a2
for i in a2:
    print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [80]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [81]:
for i in a3:
    print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [82]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [83]:
##transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [84]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
np.transpose(a3)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [86]:
## ravel
# ravel converterted d (dimentional) to 1d (dimentional)
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# STRAKING 

In [88]:
### horizantal starking 
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [89]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [90]:
# vertual stackng
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### SPLITING 

In [91]:
## horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [ ]:
### vertual splitting 
np.vsplit(a5,2)

ValueError: array split does not result in an equal division